### ISSUE TITLE
ModuleNotFoundError: No module named 'jaconv'

### ISSUE THREAD

**Issue by hkiyomaru** [ku-nlp/kwja#118]
## To reproduce

```
$ kwja --version
Traceback (most recent call last):
  File "/Users/hirokazukiyomaru/.local/bin/kwja", line 5, in <module>
    from kwja.cli.cli import app
  File "/Users/hirokazukiyomaru/.local/pipx/venvs/kwja/lib/python3.10/site-packages/kwja/cli/cli.py", line 15, in <module>
    from kwja.callbacks.word_module_discourse_writer import WordModuleDiscourseWriter
  File "/Users/hirokazukiyomaru/.local/pipx/venvs/kwja/lib/python3.10/site-packages/kwja/callbacks/word_module_discourse_writer.py", line 13, in <module>
    from kwja.datamodule.datasets import WordDataset, WordInferenceDataset
  File "/Users/hirokazukiyomaru/.local/pipx/venvs/kwja/lib/python3.10/site-packages/kwja/datamodule/datasets/__init__.py", line 1, in <module>
    from .char_dataset import CharDataset
  File "/Users/hirokazukiyomaru/.local/pipx/venvs/kwja/lib/python3.10/site-packages/kwja/datamodule/datasets/char_dataset.py", line 13, in <module>
    from kwja.datamodule.examples.char_feature import CharFeatureExample
  File "/Users/hirokazukiyomaru/.local/pipx/venvs/kwja/lib/python3.10/site-packages/kwja/datamodule/examples/__init__.py", line 5, in <module>
    from .reading import ReadingExample
  File "/Users/hirokazukiyomaru/.local/pipx/venvs/kwja/lib/python3.10/site-packages/kwja/datamodule/examples/reading.py", line 6, in <module>
    from kwja.utils.reading import ReadingAligner
  File "/Users/hirokazukiyomaru/.local/pipx/venvs/kwja/lib/python3.10/site-packages/kwja/utils/reading.py", line 8, in <module>
    import jaconv
ModuleNotFoundError: No module named 'jaconv'
```

**Comment by hkiyomaru** [comment]
I found that f85f6a1883a570616037ba8b16071eca59290bcf moved `kyoto-reader` to the dev-dependency and consequently `jaconv` was also moved to dev-dependency.

**Comment by hkiyomaru** [comment]
8581a5e6490e2242e9df70c3ccb260d8fcb6cdec fixed this issue.
